<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Automated Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            margin-bottom: 20px;
        }
        .content {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .footer {
            text-align: center;
            color: #6c757d;
            font-size: 14px;
            margin-top: 20px;
        }
        .report-info {
            background: white;
            padding: 15px;
            border-radius: 5px;
            border-left: 4px solid #007bff;
        }
        .attachment-info {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Multi-School Management System</h1>
        <h2>Automated Report</h2>
    </div>

    <div class="content">
        <h3>Hello,</h3>
        
        <p>Your scheduled report has been generated and is ready for review.</p>
        
        <div class="report-info">
            <h4>Report Details:</h4>
            <ul>
                <li><strong>Report Type:</strong> {{ ucwords(str_replace('_', ' ', $reportType)) }}</li>
                <li><strong>Generated At:</strong> {{ $generatedAt }}</li>
                <li><strong>Period:</strong> 
                    @if(isset($reportData['period']))
                        {{ $reportData['period']['start_date'] ?? 'N/A' }} to {{ $reportData['period']['end_date'] ?? 'N/A' }}
                    @else
                        As configured
                    @endif
                </li>
            </ul>
        </div>

        @if($reportType === 'system_overview' && isset($reportData['summary']))
        <div class="report-info">
            <h4>Quick Summary:</h4>
            <ul>
                <li>Total Schools: {{ $reportData['summary']['total_schools'] ?? 'N/A' }}</li>
                <li>Total Users: {{ $reportData['summary']['total_users'] ?? 'N/A' }}</li>
                <li>Total Students: {{ $reportData['summary']['total_students'] ?? 'N/A' }}</li>
                <li>Total Teachers: {{ $reportData['summary']['total_teachers'] ?? 'N/A' }}</li>
            </ul>
        </div>
        @endif

        @if($reportType === 'school_performance' && isset($reportData['system_averages']))
        <div class="report-info">
            <h4>System Averages:</h4>
            <ul>
                <li>Average Students per School: {{ $reportData['system_averages']['avg_students_per_school'] ?? 'N/A' }}</li>
                <li>Average Teachers per School: {{ $reportData['system_averages']['avg_teachers_per_school'] ?? 'N/A' }}</li>
                <li>Average Student-Teacher Ratio: {{ $reportData['system_averages']['avg_student_teacher_ratio'] ?? 'N/A' }}</li>
            </ul>
        </div>
        @endif

        @if($reportType === 'user_analytics' && isset($reportData['activity_metrics']))
        <div class="report-info">
            <h4>User Activity:</h4>
            <ul>
                <li>Total Users: {{ $reportData['activity_metrics']['total_users'] ?? 'N/A' }}</li>
                <li>Active Users: {{ $reportData['activity_metrics']['active_users'] ?? 'N/A' }}</li>
                <li>Activity Rate: {{ $reportData['activity_metrics']['activity_rate'] ?? 'N/A' }}%</li>
            </ul>
        </div>
        @endif

        <div class="attachment-info">
            <h4>📎 Attachment</h4>
            <p>The complete report is attached to this email. Please download and review the detailed data.</p>
        </div>

        <p>If you have any questions about this report or need assistance, please contact the system administrator.</p>
        
        <p>Best regards,<br>
        Multi-School Management System</p>
    </div>

    <div class="footer">
        <p>This is an automated message. Please do not reply to this email.</p>
        <p>Generated by Multi-School Management System &copy; {{ date('Y') }}</p>
    </div>
</body>
</html>